services:
  back:
    build: ./back
    volumes:
      - ./back:/usr/src/app
    env_file:
      - ./back/.env

    command: cargo watch -x run

    ports:
      - 127.0.0.1:5000:5000
  front:
    build: ./front
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - back
