services:
  back:
    image: ghcr.io/gregoirebellon/cellion-back:main
    env_file:
      - ./back/.env
  front:
    image: ghcr.io/gregoirebellon/cellion-front:main
    environment:
      - BACK_REF=back
    ports:
      - 8080:80
    depends_on:
      - back
