services:
  back:
    build:
      context: ./back
      dockerfile: docker/Dockerfile

    env_file:
      - ./back/.env
    command: ./target/release/back
  front:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    environment:
      - BACK_REF=back
    ports:
      - 8080:80
    depends_on:
      - back
