---
- name: Setup the app 
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - {role: geerlingguy.pip, become: true}
    - {role: geerlingguy.docker, become: true}
  
  tasks:
    - name: Logout from ghcr to be able to pull public image
      community.docker.docker_login:
        registry: "{{ cellion_docker_registry }}"
        state: absent

    - name: Start the docker-compose
      community.docker.docker_compose_v2:
        pull: "always"
        recreate: "always"
        project_name: cellion
        definition:
          services:
            back:
              image: "{{ cellion_docker_registry }}/{{ cellion_docker_back_image_name }}:{{ cellion_docker_back_image_tag }}"
              environment:
                - DATABASE_URL=/usr/src/app/val.db
                - RUST_LOG="{{ cellion_back_log_level }}"
              volumes:
                - sqlite:/usr/src/app/val.db
            front:
              image: "{{ cellion_docker_registry }}/{{ cellion_docker_front_image_name }}:{{ cellion_docker_front_image_tag }}"
              environment:
                - BACK_REF=back
              ports:
                - "{{ cellion_host }}:{{ cellion_port }}:80"
              depends_on:
                - back
          volumes:
            sqlite:

              