ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('root') }}"
ansible_host: "{{ lookup('env', 'SERVER_IP')}}"

pip_install_packages:
  - name: docker
docker_users:
  - "{{ ansible_user }}"


cellion_docker_registry: "{{ lookup('env', 'DOCKER_REGISTRY') }}"
cellion_docker_front_image_name: "{{ lookup('env', 'FRONT_IMAGE_NAME') }}"
cellion_docker_front_image_tag: "{{ lookup('env', 'FRONT_IMAGE_TAG') }}"
cellion_docker_back_image_name: "{{ lookup('env', 'BACK_IMAGE_NAME') }}"
cellion_docker_back_image_tag: "{{ lookup('env', 'BACK_IMAGE_TAG') }}"
cellion_back_log_level: "info"
cellion_port: 8080
cellion_host: "0.0.0.0"
