name: On push

on:
  push:
    branches: ["main", "feat/cd"]

jobs:
  test-front:
    uses: ./.gihub/workflows/test-front.yml

  test-back:
    uses: ./.gihub/workflows/test-back.yml

  publish-front:
    needs: test-front
    uses: ./.gihub/workflows/publish-docker.yml@main
    with:
      context: "front"
      file: "front/docker/Dockerfile"
      image-name: "${{github.repository}}-front"

  publish-back:
    needs: test-back
    uses: ./.gihub/workflows/publish-docker.yml
    with:
      context: "back"
      file: "back/docker/Dockerfile"
      image-name: "${{github.repository}}-back"
