name: On push

on:
  push:
    branches: ["main", "feat/cd"]

jobs:
  # test-front:
  #   uses: ./.github/workflows/test-front.yml

  # test-back:
  #   uses: ./.github/workflows/test-back.yml

  publish-front:
    permissions:
      contents: read
      packages: write
      attestations: write

    # needs: test-front
    uses: ./.github/workflows/publish-docker.yml
    with:
      context: "front"
      file: "front/docker/Dockerfile"
      image-name: "${{github.repository}}-front"

  publish-back:
    permissions:
      contents: read
      packages: write
      attestations: write

    # needs: test-back
    uses: ./.github/workflows/publish-docker.yml
    with:
      context: "back"
      file: "back/docker/Dockerfile"
      image-name: "${{github.repository}}-back"
