name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'back' # Here the path to the folder where package-lock.json is located.
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./back -> target"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
