name: Build and test the back

env:
  CARGO_TERM_COLOR: always

on:
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "back"
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./back -> target"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
