name: Build and test the front

on:
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "front"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
